### ISSUE TITLE
Adding multiple Networks

### ISSUE THREAD

**Issue by mjharden** [vancluever/terraform-vsphere-virtual-machine#5]
I am trying to add Multiple IP's to virtual machines, all on the same Network. Any advice would be appreciated!

**Comment by Taur1ne** [comment]
It doesn't look like the author is maintaining this repo any longer, but here's some documentation on how to add multiple NICs to a VM: https://www.terraform.io/docs/providers/vsphere/r/virtual_machine.html#network-interface-options

Looks like the https://github.com/vancluever/terraform-vsphere-virtual-machine/blob/master/vsphere_virutal_machine_linux.tf file would need to be updated to have multiple NICs. 

HTH
Cheers!

**Comment by vancluever** [comment]
I haven't maintained this module in a very long time, and I don't have the vSphere infra to test any changes on, so I'm closing this in preparation of archival.

If you found the module useful, feel free to fork it!
